# Generated by Django 3.0.1 on 2019-12-29 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookschedule', '0003_auto_20191221_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('delete', 'delete'), ('update', 'update'), ('add', 'add')], max_length=6)),
                ('user', models.CharField(choices=[('Bill', 'Bill'), ('Daniel', 'Daniel'), ('Darcy', 'Darcy'), ('Leo', 'Leo')], max_length=150)),
                ('note_previous', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Eater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bill', 'Bill'), ('Daniel', 'Daniel'), ('Darcy', 'Darcy'), ('Leo', 'Leo')], max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='cancelled',
        ),
        migrations.AlterField(
            model_name='cook',
            name='name',
            field=models.CharField(choices=[('Bill', 'Bill'), ('Daniel', 'Daniel'), ('Darcy', 'Darcy'), ('Leo', 'Leo')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Eat',
        ),
        migrations.AddField(
            model_name='eater',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookschedule.Schedule'),
        ),
    ]
