# Generated by Django 3.0.1 on 2019-12-29 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookschedule', '0004_auto_20191229_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bill', 'Bill'), ('Daniel', 'Daniel'), ('Darcy', 'Darcy'), ('Leo', 'Leo')], max_length=16)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookschedule.ChangeLog')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousCook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bill', 'Bill'), ('Daniel', 'Daniel'), ('Darcy', 'Darcy'), ('Leo', 'Leo')], max_length=16)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookschedule.ChangeLog')),
            ],
        ),
    ]
